### ISSUE TITLE
Migrate application to subdomain

### ISSUE THREAD

**Issue by janschill** [janschill/uni-devops#110]
I would prefer if the application would run on a dedicated subdomain:

- **App**: minitwit.janschill.de
- **API**: minitwit-api.janschill.de
- **Staging**: minitwit-staging.janschill.de

I have set up subdomains, but I will need to figure out, how to orchestrate those with out application.
I will also need to update the entries for the domains in the ITU DevOps repository.

**Comment by janschill** [comment]
Maybe we will just use ports ☹️ I would love to learn how to get the whole thing done with subdomains.

**Comment by Fr3d-** [comment]
I think we can fix this issue and #93 using nginx as a frontend proxting all requests. I think this blogpost is a good entrypoint in solving this with nginx: https://pthomann.pl/setup-frontend-application-on-nginx-in-5-minutes/
