### ISSUE TITLE
Create system security assessment

### ISSUE THREAD

**Issue by Fr3d-** [janschill/uni-devops#133]
- [x] Define our assets

- [x] Create a risk matrix for the entire system

- [x] Do a penetration test of our system and fix found vulnerabilities (OWASP top 10 is a good starting point)

**Comment by janschill** [comment]
@alevani is doing 1st and 2nd.
@alevani and @Fr3d- are doing the third “Do a penetration test of our system and fix found vulnerabilities (OWASP top 10 is a good starting point)”

**Comment by janschill** [comment]
Sanitize inputs is a current issue.
