### ISSUE TITLE
Write report

### ISSUE THREAD

**Issue by janschill** [janschill/uni-devops#134]
In the wiki, just export it.

The report has to contain information regarding issues: #135, #133, #137

**Comment by janschill** [comment]
Please fill out the gaps in the wiki documentation.

[Session 06](https://github.com/janschill/uni-devops/wiki/Session-06):
- [ ] Monitoring @JeppeV 

[Session 07](https://github.com/janschill/uni-devops/wiki/Session-07):
- [ ] Refactoring for Clean Subsystem Interfaces @janschill 

[Session 08](https://github.com/janschill/uni-devops/wiki/Session-08):
- [ ] SLA @Fr3d-

**Comment by janschill** [comment]
TODO:

- [] Use Kibana to analyse remote logging

**Comment by Fr3d-** [comment]
Report has been written [here](https://hackmd.io/nuAgyJsERk2mg13q0Fp8uw).
