### ISSUE TITLE
Password check is using wrong conditional, allowing every login

### ISSUE THREAD

**Issue by alexander34ro** [janschill/uni-devops#139]
### Funny story

> It will be hard finding any issues without knowing ruby.

 _...few minutes later..._

### Not that funny anymore

https://github.com/janschill/uni-devops/blob/75b27984c9b89f37552aba27851c80dd23b08ae1/app/controllers/login_controller.rb#L16

🤦‍♂ 
🤦‍♂ 
🤦‍♂ 

![image](https://user-images.githubusercontent.com/16760229/77700707-0745cc80-6fb5-11ea-9267-3a6c15be2e49.png)

**Comment by janschill** [comment]
lol oops 😅
