### ISSUE TITLE
Average response time is lower than expected

### ISSUE THREAD

**Issue by alexander34ro** [janschill/uni-devops#152]
Based on the SLA https://github.com/janschill/uni-devops/blob/master/SLA.md the mean response time for this API should be lower than 300ms. 

We've been monitoring its performance (because that's what people do randomly on the internet) and have found out that some recent changes (less than an hour ago) seem to have drastically increased the response time.  The average was calculate based on the response time obtained for the last 100 requests made to this endpoint. 

Below are the UTC timestamps at which we were able to measure an average response time of more than 300ms. Hope this can help you debug the issue.

Warning: SLA not respected! 331.25847574747473ms at 2020-03-29T12:01:40.318Z
Warning: SLA not respected! 345.57651301000004ms at 2020-03-29T12:02:49.297Z
Warning: SLA not respected! 331.54120515ms at 2020-03-29T12:03:23.465Z
Warning: SLA not respected! 307.3683589500001ms at 2020-03-29T12:03:58.214Z
Warning: SLA not respected! 324.8572029100001ms at 2020-03-29T12:04:30.712Z
Warning: SLA not respected! 333.82745206ms at 2020-03-29T12:05:32.368Z
Warning: SLA not respected! 310.27656697000003ms at 2020-03-29T12:06:34.875Z
Warning: SLA not respected! 338.84986205999996ms at 2020-03-29T12:07:41.330Z
Warning: SLA not respected! 314.3734300799998ms at 2020-03-29T12:09:07.671Z

**Comment by alexander34ro** [comment]
This is still happening at 1 hour after detecting the issue.

Warning: SLA not respected! 344.08710704000003ms at 2020-03-29T12:21:58.715Z
Warning: SLA not respected! 302.54646008ms at 2020-03-29T12:30:11.992Z
Warning: SLA not respected! 311.54345598000003ms at 2020-03-29T12:30:48.155Z

**Comment by alexander34ro** [comment]
This seems to be getting worse

Error: FetchError: request to http://janschill.de:1337/latest failed, reason: getaddrinfo ENOTFOUND janschill.de 2020-03-29T14:33:19.133Z
Error: FetchError: request to http://janschill.de:1337/latest failed, reason: getaddrinfo ENOTFOUND janschill.de 2020-03-29T14:33:19.135Z
Error: FetchError: request to http://janschill.de:1337/latest failed, reason: getaddrinfo ENOTFOUND janschill.de 2020-03-29T14:33:19.141Z
Error: FetchError: request to http://janschill.de:1337/latest failed, reason: getaddrinfo ENOTFOUND janschill.de 2020-03-29T14:33:19.202Z
Warning: SLA not respected! 311.0273420500001ms at 2020-03-29T14:42:27.173Z

**Comment by alexander34ro** [comment]
New warnings

Warning: SLA not respected! 400.92386697000006ms at 2020-03-29T19:32:50.669Z
Warning: SLA not respected! 320.28092711ms at 2020-03-29T19:33:34.709Z

**Comment by alevani** [comment]
Hi @alexander34ro , concerning the average response time : Do you calculate the actual average ? Because average means that some request make take up to more than 300ms to response and others less, which balance (average) to 300ms. Concerning https://github.com/janschill/uni-devops/issues/152#issuecomment-605654491, Have you gotten any new of these ?

**Comment by alexander34ro** [comment]
@alevani yes, as mentioned above, those numbers represent the average time for the last 100 requests. 

There have been no new 404s recently, the last event was an average response time of 329.43031309ms at 2020-03-30T11:04:34.450Z

**Comment by alevani** [comment]
@alexander34ro Thanks ! It was just to makes things clear. We will investigate.

**Comment by alexander34ro** [comment]
Error: FetchError: request to http://janschill.de:1337/latest failed, reason: getaddrinfo ENOTFOUND janschill.de 2020-03-30T17:55:01.782Z
Error: FetchError: request to http://janschill.de:1337/latest failed, reason: getaddrinfo ENOTFOUND janschill.de 2020-03-30T17:55:01.828Z
Error: FetchError: request to http://janschill.de:1337/latest failed, reason: getaddrinfo ENOTFOUND janschill.de 2020-03-30T17:55:01.917Z
Error: FetchError: request to http://janschill.de:1337/latest failed, reason: getaddrinfo ENOTFOUND janschill.de 2020-03-30T17:55:01.969Z
Error: FetchError: request to http://janschill.de:1337/latest failed, reason: getaddrinfo ENOTFOUND janschill.de 2020-03-30T17:55:01.986Z
Error: FetchError: request to http://janschill.de:1337/latest failed, reason: getaddrinfo ENOTFOUND janschill.de 2020-03-30T17:55:02.031Z
Error: FetchError: request to http://janschill.de:1337/latest failed, reason: getaddrinfo ENOTFOUND janschill.de 2020-03-30T17:55:02.117Z
