### ISSUE TITLE
Security Report from Blanao Systems (Group L)

### ISSUE THREAD

**Issue by alexander34ro** [janschill/uni-devops#165]
# Group A Security Report

While monitoring and white hacking Group A we found multiple nonconformities with their SLA and a handful of vulnerabilities.

## Monitoring

Our own script was used to test the SLA of Group A. We offered an ideal scenario for connecting to their API. As a result, we were surprised to observe multiple moments of nonconformity in the first few days of monitoring. This is further detailed in #152

### Authentication

As described in #139, we uncovered a gross error in their authentication system that allowed everybody to bypass the password check and log in by knowing just the email. Making things even worse, they were checking the plain text passwords during authentication.

 ### Sanitization

This was a known error at the time of writing this report, described in issue #80. The targeted website was using minimal sanitization and, as a consequence, it was vulnerable to most injection attacks.

### General

The language of choice here is Ruby with no additional framework. Upon inspection, the Rails framework mitigates the following security vulnerabilities that are probably present in this Ruby-only application:

* Cross-Site Scripting (XSS)
* Cross-Site Request Forgery (CSRF)
* Cookie hijacking

**Comment by Fr3d-** [comment]
Thanks for the feedback.
