### ISSUE TITLE
Write final report

### ISSUE THREAD

**Issue by janschill** [janschill/uni-devops#193]

**Comment by janschill** [comment]
- [ ] Dependency graph for APP and API
- [ ] Argue for about ORM
- [ ] Talk about database switch

**Comment by alevani** [comment]
CD/CI chain @alevani 
Github action @janschill
 -> say: we use GitHub Actions to upload multiple files to servers
-> user ruby tool to test our code
-> talk about the code analyyis tool
-> talk about sonar cloud
https://github.com/janschill/uni-devops/wiki/Session-07


Talk about :
- evolution and refactoring
- operation, and maintenance
- of your ITU-MiniTwit systems. Link back to respective commit messages, issues, tickets, etc. to illustrate these.

- database migration
- should have added indexes to the database? 
- migration issues
