### ISSUE TITLE
Question/answer sheet

### ISSUE THREAD

**Issue by janschill** [janschill/uni-devops#195]
Produce a list with questions that might be asked in the oral exam, so we are all on the same page and have a good preparation.

**Comment by janschill** [comment]
[Google docs](https://docs.google.com/document/d/1btWtJMCg3VJHCO9EIoSjV40Rj1PhROBeIvbCSP4FnrM/edit?usp=sharing)

**Comment by JeppeV** [comment]
Align sheet with report
