### ISSUE TITLE
Refactor controller to do all logic in them

### ISSUE THREAD

**Issue by alevani** [janschill/uni-devops#34]

**Comment by JeppeV** [comment]
https://www.rubydoc.info/gems/roda/1.3.0
Under composition, allows to route to other classes (controllers)

**Comment by janschill** [comment]
Maybe with a refactor of the controllers, we should also look at using `hash_routes`: https://roda.jeremyevans.net/rdoc/files/doc/conventions_rdoc.html

**Comment by janschill** [comment]
A nicely sized Rails application that could be used for some architectural inspirations: https://github.com/scaffeinate/socify
