### ISSUE TITLE
[04] Fix image on post

### ISSUE THREAD

**Issue by alevani** [janschill/uni-devops#56]
When I publish a post on the minitwit, the image does not appear. see :
<img width="170" alt="Screenshot 2020-02-26 at 22 09 45" src="https://user-images.githubusercontent.com/28229423/75388109-b3c45e00-58e4-11ea-8c0a-bd40ab4981d1.png">

**Comment by Fr3d-** [comment]
This is the culprit:
https://github.com/janschill/uni-devops/blob/7d965fdfc47b3ccb38be35a617624fc8173fae6d/app/views/timeline.erb#L28

How do we want avatars to handle avatars? we could give users a random avatar like Github?

**Comment by Fr3d-** [comment]
i am dumb
