### ISSUE TITLE
Sanitize inputs

### ISSUE THREAD

**Issue by janschill** [janschill/uni-devops#80]

**Comment by alexander34ro** [comment]
Double checked and it looks like your inputs need sanitization to prevent basic injections.

![image](https://user-images.githubusercontent.com/16760229/77702287-74a72c80-6fb8-11ea-83cb-53143299e78d.png)

You SQL seems alright as you are using the safe ruby methods for most of your queries. There are a few places that are using raw SQL but those seem to be still automatically sanitized and we didn't manage to drop the Users table... yet.

**Comment by janschill** [comment]
Hey @alexander34ro, please don't drop the table haha. Thanks for letting us know and even comment on the correct issue!
