### ISSUE TITLE
Don't copy everything from the project into the Docker container

### ISSUE THREAD

**Issue by janschill** [janschill/uni-devops#88]
There are a lot of files that we do not need in the production Docker image/container. This can be easily fixed by only copying the exact files we need.

**Comment by alevani** [comment]
Could you please provide a description of the file we don't need in the container so we can go forward with the issue ?

**Comment by Fr3d-** [comment]
Right now it's only `/app` and `/api` that gets copied to the docker image, which we both need.

**Comment by janschill** [comment]
No, but in those folders there is a lot that does not need to be there. I will produce a list.
