### ISSUE TITLE
Ensure 100% uptime during deploy

### ISSUE THREAD

**Issue by janschill** [janschill/uni-devops#93]

**Comment by alevani** [comment]
I am not sure how we would ensure a 100% up-time during the deploy. There is always a moment where the website will not be able to receive any requests

**Comment by Fr3d-** [comment]
What we have to do is to spawn the updated service, such that we have two running versions of Minitwit, and then when both are up and running we take down the old version. For this to work I assume we need some kind of frontend where the traffic comes through that points to one of the Minitwits.

**Comment by janschill** [comment]
@Fr3d- this is done due to our new deployment strategy and infrastructure, correct?

**Comment by Fr3d-** [comment]
> @Fr3d- this is done due to our new deployment strategy and infrastructure, correct?

Yes
